### ISSUE TITLE
Disappearing Player Shadow/Player Shadow Not Showing In Some Maps

### ISSUE THREAD

**Issue by ScottVordem** [Xenthio/RealCSM#10]
I've reported this before on Steam, but I have some additional Information.

In some maps, the player shadow never shows and in the ones that do, it will disappear in certain locations. The shadow is mostly hidden unfortunately.

I would provide a list of maps, but the list would be very big, so I think the one I'll link to will suffice.

rp_city34_rz_v2 https://steamcommunity.com/sharedfiles/filedetails/?id=2712359761

I had StormFox 2 enabled.

Coordinates: x=879, y=-1655, z=108 ( outside facing away from the entrance to the train station, it is on top of the right trashcan in the small park in the plaza).

Standing on the trashcan (or off the ground), the shadow is there. The moment I touch the ground, The shadow disappears.

Also, noclipping around, the shadow also disappears when going past the trees in the same park.

Don't know why this is happening, but I tried to be as detailed as possible to hopefully help you find the cause.

**Comment by Xenthio** [comment]
Ah hmm not sure, I'll look into it

**Comment by Xenthio** [comment]
Either this issue is something on your side or I fixed it with the previous update (I didn't test before hand whoops), tell me if it still happens for you
