### ISSUE TITLE
Weird Color Issue

### ISSUE THREAD

**Issue by ScottVordem** [Xenthio/RealCSM#21]
![image](https://user-images.githubusercontent.com/107659193/182477324-8068b57e-595b-4f76-837d-4424a4c579f1.png)

I do not know what happened, I just started up Garry's Mod, but I know it does not look like this originally. It happens on any map, but the screenshot was taken in gm_construct. I didn't change anything major in CSM itself.

I do have StormFox 2 enabled.

**Comment by Xenthio** [comment]
> ![image](https://user-images.githubusercontent.com/107659193/182477324-8068b57e-595b-4f76-837d-4424a4c579f1.png)
> 
> 
> 
> 
> 
> I do not know what happened, I just started up Garry's Mod, but I know it does not look like this originally. It happens on any map, but the screenshot was taken in gm_construct. I didn't change anything major in CSM itself.
> 
> 
> 
> I do have StormFox 2 enabled.

Did you enable csm_debug_cascades?

**Comment by ScottVordem** [comment]
No I didn't, but it was enabled already, I did not touch that setting before. Turning it off fixed it but I am confused how it was turned on.

**Comment by Xenthio** [comment]
Yeah woops my bad, I accidentally left it enabled by default in the code :)
I have fixed this issue now.
