### ISSUE TITLE
Auto Spawn randomly stopped working

### ISSUE THREAD

**Issue by ScottVordem** [Xenthio/RealCSM#23]
I literally don't know how it broke or what caused it, so I doubt I can be much help in troubleshooting.

I noticed randomly that all maps (including default Garry's Mod maps) were not having CSM shadows, then it started working after I spawned the CSM editor manually. The auto spawn feature does not work for me anymore and I have to spawn the entity in randomly.

**Comment by ScottVordem** [comment]
Yes, the option is on. I have tried toggling it and restarting and it is still not working.

**Comment by Xenthio** [comment]
does this happen without any other addons installed?

**Comment by ScottVordem** [comment]
It only happens with addons installed, however I do not have any addons that would prevent CSM from spawning. I have no idea which one it could be or how to find it. Are there any commands I can try?

**Comment by ScottVordem** [comment]
OH WAIT! I found the culprit and it literally does not make sense as to why it prevents the auto spawn from working.

It is [this addon](https://steamcommunity.com/sharedfiles/filedetails/?id=2858378115). It is a fairly new addon, not an old one.

**Comment by Xenthio** [comment]
> OH WAIT! I found the culprit and it literally does not make sense as to why it prevents the auto spawn from working.
> 
> 
> 
> It is [this addon](https://steamcommunity.com/sharedfiles/filedetails/?id=2858378115). It is a fairly new addon, not an old one.

You should probably report this bug on their addon too, I'll take a look into what causes this when I can

**Comment by Xenthio** [comment]
> > OH WAIT! I found the culprit and it literally does not make sense as to why it prevents the auto spawn from working.
> > It is [this addon](https://steamcommunity.com/sharedfiles/filedetails/?id=2858378115). It is a fairly new addon, not an old one.
> 
> You should probably report this bug on their addon too, I'll take a look into what causes this when I can

the addon dev has said he has fixed the issue on his side so pls tell me if it all works :) if i don't recieve a reply i'll close this issue anyways and assume it's fixed

**Comment by ScottVordem** [comment]
Yep! Auto spawn is working with that addon enabled!
