### ISSUE TITLE
HL2 skybox doesn't work properly with CSM on multiplayer session

### ISSUE THREAD

**Issue by EuroSzymon** [Xenthio/RealCSM#28]
It works as intended on singleplayer session but it doesn't work very well on multiplayer session and skybox is bugging with half of black texture.
![Zrzut ekranu 2023-11-25 141507](https://github.com/Xenthio/RealCSM/assets/104522234/ed6ca180-2dbe-4aa0-885e-05f84d9312b5)

**Comment by EuroSzymon** [comment]
This bug doesn't appear in maps with **painted skybox** (like default GMod maps are using) but i think that it requires fixing support of CSM for HL2 skyboxes.

**Comment by EuroSzymon** [comment]
I identified that the problem leads to that CSM uses commands that are cheat-protected on servers and it's required to unlock them by sv_cheats command but it would be cool if mod would use necessary commands without requiring to unlock them by sv_cheats.

**Comment by EuroSzymon** [comment]
>  This bug doesn't appear in maps with painted skybox (like default GMod maps are using) even on multiplayer session but i think that it requires fixing support of CSM for HL2 skyboxes.

Also i'm changing this because it happens on all skyboxes.

**Comment by Xenthio** [comment]
Fixed
